# Generated by Django 3.1.13 on 2021-10-11 11:44

import cvat.apps.engine.models
from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_manufacture', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('video', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='storage',
            field=models.CharField(choices=[('cloud_storage', 'CLOUD_STORAGE'), ('local', 'LOCAL'), ('share', 'SHARE')], default=cvat.apps.engine.models.StorageChoice['CLOUD_STORAGE'], max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='storage_method',
            field=models.CharField(choices=[('cache', 'CACHE'), ('file_system', 'FILE_SYSTEM'), ('cloud_storage', 'CLOUD_STORAGE')], default=cvat.apps.engine.models.StorageMethodChoice['FILE_SYSTEM'], max_length=15),
        ),
    ]
